preprocess:
  input: data/raw/diabetes.csv
  output: data/processed/diabetes_clean.csv

train:
  data: data/raw/diabetes.csv    
  model: models/diabetes_model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 5
  